name: Build source code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: npm run setup

      - name: Lint
        run: npm run lint
        working-directory: ./src

      - name: Run unit tests
        run: npm run test:ci
        working-directory: ./src

      - name: Run E2E tests
        run: npm run cy:chrome
        working-directory: ./src

      - name: Package screenshots from E2E tests
        # if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: src/cypress/screenshots

      - name: Build component library for production
        run: npm run build-library
        working-directory: ./src

      - name: Build demo-project for production
        run: npm run build-showroom
        working-directory: ./
