name: Build targeting Angular v11

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build targeting Angular v11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run setup
      - run: npm run build-library-v11

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: temp/library-v11/src/dist