name: Build source code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run setup
      
      - run: npm run lint
        working-directory: ./src

      - run: npm run cy:chrome
        working-directory: ./src

      - run: npm run build-library
        working-directory: ./src