# This is a basic workflow to help you get started with Actions

name: Lint, Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm run setup

      - run: npm run lint
        working-directory: ./src

      - run: npm run cy:chrome
        working-directory: ./src

      - run: npm run build-library
        working-directory: ./src