name: Build targeting Angular v9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    uses: flaeng/ngfds/.github/workflows/build-angular.yml@main
    with:
      ngVersion: 9