name: Build source code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: npm run setup

      - name: lint
        run: npm run lint
        working-directory: ./src

      - name: cypress
        run: npm run cy:chrome
        working-directory: ./src

      - name: Package screenshots
        if: ${{ failure() && steps.cypress.outcome == 'failure' }}
        # if: failure() && steps.cypress.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: src/cypress/screenshots

      - run: npm run build-library
        working-directory: ./src