name: Build targeting Angular v15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build targeting next Angular version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run setup
      - run: npm run build-library-next

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: temp/library-next/src/dist