name: Build source code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: npm run setup

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint
        run: npm run lint
        working-directory: src

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run unit tests
        run: npm run test:ci
        working-directory: src

  e2e-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run E2E tests
        run: npm run cy:chrome
        working-directory: src

      - name: Package screenshots from E2E tests
        # if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: src/cypress/screenshots

  build-library:
    runs-on: ubuntu-latest
    needs: [setup,lint,unit-tests,e2e-tests]
    steps:
      - name: Build component library for production
        run: npm run build-library
        working-directory: src

  build-app:
    runs-on: ubuntu-latest
    needs: [setup,lint,unit-tests,e2e-tests]
    steps:
      - name: Build demo-project for production
        run: npm run build-showroom
        working-directory:
