name: Build for Angular

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 12 * * 5"

jobs:
  build:
    name: Build for Angular
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # ng-version: ["v9", "v10", "v11", "v12", "v13", "v14", "v15"]
        ng-version: ["v11", "v12", "v13", "v14", "v15"]

    steps:
      - uses: actions/checkout@v3
      - run: npm run setup

      - run: npm run ${{ format('build-library-{0}', matrix.ng-version) }}

      - run: node ../scripts/icon-packer.js
        working-directory: ./src
      - run: node ../scripts/generate-docs.js
        working-directory: ./src

      - run: npm run ${{ format('setup-demo-{0}', matrix.ng-version) }}

      # - run: npx cypress run --component -b chrome -C ${{ format('temp/demo-project-{0}/src/projects/demo-project/cypress.config.ts', matrix.ng-version) }} -s ${{ format('temp/demo-project-{0}/src/projects/ngfds/cypress/e2e/**/*.cy.ts', matrix.ng-version) }}
        # working-directory: ${{ format('temp/demo-project-{0}', matrix.ng-version) }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('library-{0}', matrix.ng-version) }}
          path: ${{ format('temp/library-{0}/src/dist', matrix.ng-version) }}
