# This is a basic workflow to help you get started with Actions

name: E2E tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm install in root
        run: npm install

      - name: npm install in src
        run: npm install
        working-directory: ./src

      - run: npm run cy:chrome
        working-directory: ./src